create table
  public.invoice (
    id bigint generated by default as identity,
    status text null default 'pending'::text,
    total_amount real null,
    created_at timestamp without time zone not null default now(),
    due_date timestamp without time zone null,
    update_at timestamp without time zone null,
    interest_rate real null,
    interest_amount real null,
    customer_id bigint null default '1'::bigint,
    constraint Invoice_pkey primary key (id),
    constraint invoice_id_key unique (id)
  ) tablespace pg_default;

  create table
  public.invoice_invoice_item (
    id_invoice bigint not null,
    id_invoice_item bigint not null,
    constraint invoice_invoice_item_pkey primary key (id_invoice, id_invoice_item),
    constraint invoice_invoice_item_id_invoice_fkey foreign key (id_invoice) references invoice (id),
    constraint invoice_invoice_item_id_invoice_item_fkey foreign key (id_invoice_item) references invoice_item (id)
  ) tablespace pg_default;

  create table
  public.invoice_item (
    id bigint generated by default as identity,
    created_at timestamp without time zone not null default now(),
    description text null,
    quantity integer null default 0,
    unit_price double precision null,
    total_amount double precision null,
    constraint invoice_item_pkey primary key (id),
    constraint invoice_item_id_key unique (id)
  ) tablespace pg_default;

  create table
  public.payment (
    id bigint generated by default as identity,
    created_at timestamp without time zone not null default now(),
    invoice_id bigint null,
    amount double precision null,
    paymen_date timestamp without time zone null,
    payment_method text null,
    constraint payment_pkey primary key (id),
    constraint payment_id_key unique (id),
    constraint payment_invoice_id_fkey foreign key (invoice_id) references invoice (id) on delete cascade
  ) tablespace pg_default;

  create table
  public.refund (
    id bigint generated by default as identity,
    created_at timestamp without time zone not null default now(),
    invoice_id bigint null,
    amount double precision null,
    refund_date timestamp without time zone null,
    reason text null,
    constraint refund_pkey primary key (id),
    constraint refund_id_key unique (id),
    constraint refund_invoice_id_fkey foreign key (invoice_id) references invoice (id) on delete cascade
  ) tablespace pg_default;